### ISSUE TITLE
Page not changing on swipe if page is zoomed

### ISSUE THREAD

**Issue by khalid-mahmood** [barteksc/AndroidPdfViewerV1#11]
if i have zoomed page then page change using swipe is not working. any solution ?

**Comment by barteksc** [comment]
It is desired behavior

**Comment by khalid-mahmood** [comment]
@barteksc is this behavior added ?

**Comment by barteksc** [comment]
Sorry, I don't understand. Added to what?
You cannot change page in zoom mode, it is intentional

**Comment by khalid-mahmood** [comment]
can you please guide if i want to do this..
page change while page is zoomed.
??

**Comment by barteksc** [comment]
I wrote: you cannot change page in zoom mode.
